--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Gewinum/auth-system
build-by-default: true
branches:
- master
projects:
    AuthSystem:
        path: ./
        logo: icon.png
        libs:
            - src: poggit/libasynql/libasynql
              version: ^4.1
...